# Python - 2.7.6

Test.describe('Basic tests')
Test.it('should work for fixed tests (provided in the description)')
Test.assert_equals(to_alternating_case('hello world'), 'HELLO WORLD')
Test.assert_equals(to_alternating_case('HELLO WORLD'), 'hello world')
Test.assert_equals(to_alternating_case('hello WORLD'), 'HELLO world')
Test.assert_equals(to_alternating_case('HeLLo WoRLD'), 'hEllO wOrld')
Test.assert_equals(to_alternating_case('12345'), '12345')
Test.assert_equals(to_alternating_case('1a2b3c4d5e'), '1A2B3C4D5E')
Test.assert_equals(to_alternating_case('String.prototype.toAlternatingCase'), 'sTRING.PROTOTYPE.TOaLTERNATINGcASE')
Test.assert_equals(to_alternating_case(to_alternating_case('Hello World')), 'Hello World')
Test.it('should work for the title of this Kata')
title = 'altERnaTIng cAsE'
title = to_alternating_case(title)
Test.assert_equals(title, 'ALTerNAtiNG CaSe')
title = to_alternating_case(title)
Test.assert_equals(title, 'altERnaTIng cAsE')
title = to_alternating_case(title)
Test.assert_equals(title, 'ALTerNAtiNG CaSe')
title = to_alternating_case(title)
Test.assert_equals(title, 'altERnaTIng cAsE')
title = 'altERnaTIng cAsE <=> ALTerNAtiNG CaSe'
title = to_alternating_case(title)
Test.assert_equals(title, 'ALTerNAtiNG CaSe <=> altERnaTIng cAsE')
title = to_alternating_case(title)
Test.assert_equals(title, 'altERnaTIng cAsE <=> ALTerNAtiNG CaSe')
title = to_alternating_case(title)
Test.assert_equals(title, 'ALTerNAtiNG CaSe <=> altERnaTIng cAsE')
title = to_alternating_case(title)
Test.assert_equals(title, 'altERnaTIng cAsE <=> ALTerNAtiNG CaSe')
