# Python - 3.6.0

Test.describe("Your 'xor' function/operator")
Test.it('should work for the four basic cases described above')
Test.assert_equals(xor(False, False), False, 'False xor False == False')
Test.assert_equals(xor(True, False), True, 'True xor False == True')
Test.assert_equals(xor(False, True), True, 'False xor True == True')
Test.assert_equals(xor(True, True), False, 'True xor True == False')
Test.it('should work properly when nested')
Test.assert_equals(xor(False, xor(False, False)), False)
Test.assert_equals(xor(xor(True, False), False), True)
Test.assert_equals(xor(xor(True, True), False), False)
Test.assert_equals(xor(True, xor(True, True)), True)
Test.assert_equals(xor(xor(False, False), xor(False, False)), False)
Test.assert_equals(xor(xor(False, False), xor(False, True)), True)
Test.assert_equals(xor(xor(True, False), xor(False, False)), True)
Test.assert_equals(xor(xor(True, False), xor(True, False)), False)
Test.assert_equals(xor(xor(True, True), xor(True, False)), True)
Test.assert_equals(xor(xor(True, xor(True, True)), xor(xor(True, True), False)), True)
